name: Automated website Test

on: workflow_dispatch

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
    - name: Download every website files from repo.
      run: |
        sudo apt install -yq git
        git clone https://github.com/ItzCuteAkemi/itzcuteakemi.github.io $PWD/website

    - name: Install Puppeteer.
      run: |
        bash -c "cd website; sudo apt -yq install nodejs; npm i puppeteer puppeteer-screen-recorder"
    - name: Triggering the test.
      run: |
        bash -c "cd website; node index"
    - name: Test complete
      run: |
        echo Your test has been completed successfully. Download the test result from Webserver to see the result
        wget "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
        tar -xvf ngrok-v3-stable-linux-amd64.tgz
        sudo cp ngrok /usr/bin
        sudo apt install apache2
        sudo systemctl start apache2
        sudo cp -r $PWD /var/www/html
        